import { StyleSheet } from 'react-native';

import { Platform } from 'react-native';

const toRgba = (color: string, opacity: number): string => {
  const normalized = String(color || '').trim();
  if (!normalized) return `rgba(0, 0, 0, ${opacity})`;
  if (normalized.startsWith('rgba(') || normalized.startsWith('rgb(')) return normalized;

  const hex = normalized.replace(/^#/, '');
  if (hex.length !== 3 && hex.length !== 6) return normalized;
  const expanded =
    hex.length === 3 ? hex.split('').map((part) => `${part}${part}`).join('') : hex;
  const red = Number.parseInt(expanded.slice(0, 2), 16);
  const green = Number.parseInt(expanded.slice(2, 4), 16);
  const blue = Number.parseInt(expanded.slice(4, 6), 16);
  return `rgba(${red}, ${green}, ${blue}, ${opacity})`;
};

const buildViewShadow = (input: {
  color: string;
  opacity: number;
  radius: number;
  offsetY: number;
  elevation: number;
}): Record<string, unknown> =>
  Platform.OS === 'web'
    ? {
        boxShadow: `0px ${input.offsetY}px ${input.radius}px ${toRgba(input.color, input.opacity)}`,
      }
    : {
        shadowColor: input.color,
        shadowOpacity: input.opacity,
        shadowRadius: input.radius,
        shadowOffset: { width: 0, height: input.offsetY },
        elevation: input.elevation,
      };

const buildTextShadow = (input: { color: string; radius: number }): Record<string, unknown> =>
  Platform.OS === 'web'
    ? {
        textShadow: `0px 0px ${input.radius}px ${input.color}`,
      }
    : {
        textShadowColor: input.color,
        textShadowOffset: { width: 0, height: 0 },
        textShadowRadius: input.radius,
      };

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#121212',
    position: 'relative',
  },
  backdropLayer: {
    ...StyleSheet.absoluteFillObject,
    overflow: 'hidden',
    backgroundColor: '#121212',
  },
  backdropBandTop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 220,
    backgroundColor: 'rgba(138, 154, 91, 0.08)',
  },
  backdropBandBottom: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 220,
    backgroundColor: 'rgba(165, 113, 100, 0.08)',
  },
  backdropRuleVerticalA: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 28,
    width: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
  },
  backdropRuleVerticalB: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    right: 28,
    width: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
  },
  backdropRuleHorizontalA: {
    position: 'absolute',
    top: 132,
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
  },
  backdropRuleHorizontalB: {
    position: 'absolute',
    bottom: 188,
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
  },
  pageMotion: {
    flex: 1,
  },
  container: {
    paddingHorizontal: 18,
    paddingTop: 24,
    paddingBottom: 32,
    gap: 16,
  },
  containerWithTabs: {
    paddingBottom: 138,
  },
  heroCard: {
    position: 'relative',
    backgroundColor: 'rgba(23, 23, 23, 0.85)',
    borderColor: 'rgba(255, 255, 255, 0.1)',
    borderWidth: 1,
    borderRadius: 32,
    paddingHorizontal: 24,
    paddingVertical: 24,
    gap: 8,
    overflow: 'hidden',
    ...buildViewShadow({ color: '#121212', opacity: 0.6, radius: 24, offsetY: 12, elevation: 8 }),
  },
  heroAccent: {
    position: 'absolute',
    top: 12,
    left: 20,
    width: 84,
    height: 5,
    borderRadius: 999,
    backgroundColor: '#8A9A5B',
  },
  heroTicketRow: {
    marginTop: 2,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  heroTicketDotSage: {
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: '#8A9A5B',
  },
  heroTicketDotClay: {
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: '#A57164',
  },
  heroTicketDash: {
    width: 28,
    height: 2,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 255, 255, 0.24)',
  },
  heroEyebrow: {
    color: '#A57164',
    fontSize: 11,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  title: {
    color: '#E5E4E2',
    fontSize: 29,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
    lineHeight: 34,
  },
  subtitle: {
    color: '#c9c6bf',
    fontSize: 14,
    fontFamily: 'Inter_500Medium',
    lineHeight: 20,
    marginBottom: 8,
  },
  heroMetaRow: {
    marginTop: 0,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  surfaceIntroCard: {
    backgroundColor: 'rgba(23, 23, 23, 0.85)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 10,
  },
  surfaceIntroAccent: {
    width: 34,
    height: 4,
    borderRadius: 999,
  },
  surfaceIntroAccentSage: {
    backgroundColor: '#8A9A5B',
  },
  surfaceIntroAccentClay: {
    backgroundColor: '#A57164',
  },
  surfaceIntroTitle: {
    color: '#E5E4E2',
    fontSize: 15,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
  },
  surfaceIntroBody: {
    color: '#c9c6bf',
    fontSize: 12,
    fontFamily: 'Inter_400Regular',
    lineHeight: 18,
  },
  surfaceIntroMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  surfaceIntroBadge: {
    backgroundColor: 'rgba(138, 154, 91, 0.18)',
    borderColor: '#8A9A5B',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    color: '#E5E4E2',
    fontSize: 11,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  surfaceIntroBadgeMuted: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderColor: 'rgba(255, 255, 255, 0.24)',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    color: '#E5E4E2',
    fontSize: 11,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  navScene: {
    backgroundColor: '#121212',
  },
  navTabBar: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 16,
    backgroundColor: 'rgba(18, 18, 18, 0.92)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderRadius: 32,
    height: 84,
    paddingBottom: 12,
    paddingTop: 10,
    ...buildViewShadow({ color: '#121212', opacity: 0.5, radius: 20, offsetY: 10, elevation: 8 }),
  },
  navTabLabel: {
    fontSize: 10,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
    letterSpacing: 0.45,
    textTransform: 'uppercase',
  },
  navTabItem: {
    paddingTop: 4,
    paddingBottom: 4,
  },
  navTabBadge: {
    backgroundColor: '#A57164',
    color: '#E5E4E2',
    borderColor: '#171717',
    borderWidth: 1,
    fontSize: 10,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '700',
    minWidth: 18,
    height: 18,
    paddingHorizontal: 4,
    lineHeight: 13,
    borderRadius: 999,
    top: 2,
  },
  bottomTabBar: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 10,
    backgroundColor: 'rgba(23, 23, 23, 0.95)',
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderWidth: 1,
    borderRadius: 16,
    padding: 8,
  },
  bottomTabRow: {
    flexDirection: 'row',
    gap: 8,
  },
  statusRail: {
    marginTop: 6,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  opsSummaryRow: {
    marginTop: 2,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  opsSummaryCard: {
    minWidth: 98,
    flexGrow: 1,
    backgroundColor: 'rgba(31, 31, 31, 0.7)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 4,
  },
  opsSummaryKey: {
    color: '#8e8b84',
    fontSize: 10,
    fontFamily: 'Inter_500Medium',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  opsSummaryValue: {
    color: '#E5E4E2',
    fontSize: 13,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
  },
  statusPill: {
    minWidth: 96,
    flexGrow: 1,
    backgroundColor: 'rgba(31, 31, 31, 0.7)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 4,
  },
  statusPillKey: {
    color: '#8e8b84',
    fontSize: 10,
    fontFamily: 'Inter_500Medium',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  statusPillValue: {
    color: '#E5E4E2',
    fontSize: 12,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  statusPillValueSage: {
    color: '#8A9A5B',
  },
  statusPillValueClay: {
    color: '#A57164',
  },
  heroBadge: {
    backgroundColor: 'rgba(138, 154, 91, 0.18)',
    borderColor: '#8A9A5B',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    color: '#E5E4E2',
    fontSize: 11,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  heroBadgeMuted: {
    backgroundColor: 'rgba(165, 113, 100, 0.18)',
    borderColor: '#A57164',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    color: '#E5E4E2',
    fontSize: 11,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  heroBadgeNeutral: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderColor: 'rgba(255, 255, 255, 0.26)',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    color: '#E5E4E2',
    fontSize: 11,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  screenCard: {
    backgroundColor: 'rgba(23, 23, 23, 0.85)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderRadius: 24,
    padding: 20,
    gap: 14,
    ...buildViewShadow({ color: '#121212', opacity: 0.4, radius: 20, offsetY: 10, elevation: 6 }),
  },
  screenCardAccent: {
    width: 48,
    height: 4,
    borderRadius: 999,
    marginBottom: 2,
  },
  screenCardAccentSage: {
    backgroundColor: '#8A9A5B',
  },
  screenCardAccentClay: {
    backgroundColor: '#A57164',
  },
  sectionLeadEyebrow: {
    color: '#A57164',
    fontSize: 10,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '700',
    letterSpacing: 1.4,
    textTransform: 'uppercase',
  },
  sectionLeadTitle: {
    color: '#E5E4E2',
    fontSize: 24,
    lineHeight: 28,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
  },
  sectionLeadBody: {
    color: '#c9c6bf',
    fontSize: 13,
    lineHeight: 20,
    fontFamily: 'Inter_400Regular',
  },
  sectionLeadBadgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  sectionLeadBadge: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  sectionLeadBadgeSage: {
    backgroundColor: 'rgba(138, 154, 91, 0.14)',
    borderColor: 'rgba(138, 154, 91, 0.35)',
  },
  sectionLeadBadgeClay: {
    backgroundColor: 'rgba(165, 113, 100, 0.14)',
    borderColor: 'rgba(165, 113, 100, 0.35)',
  },
  sectionLeadBadgeMuted: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderColor: 'rgba(255, 255, 255, 0.12)',
  },
  sectionLeadBadgeText: {
    color: '#E5E4E2',
    fontSize: 10,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  sectionLeadMetricRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  sectionLeadMetricCard: {
    minWidth: 88,
    flexGrow: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.035)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 4,
  },
  sectionLeadMetricValue: {
    color: '#E5E4E2',
    fontSize: 18,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
  },
  sectionLeadMetricLabel: {
    color: '#8e8b84',
    fontSize: 10,
    fontFamily: 'Inter_500Medium',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  sectionLeadActionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  statusStrip: {
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 6,
  },
  statusStripToneSage: {
    backgroundColor: 'rgba(138, 154, 91, 0.1)',
    borderColor: 'rgba(138, 154, 91, 0.28)',
  },
  statusStripToneClay: {
    backgroundColor: 'rgba(165, 113, 100, 0.1)',
    borderColor: 'rgba(165, 113, 100, 0.28)',
  },
  statusStripToneMuted: {
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderColor: 'rgba(255, 255, 255, 0.12)',
  },
  statusStripEyebrow: {
    color: '#8e8b84',
    fontSize: 10,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  statusStripTitle: {
    color: '#E5E4E2',
    fontSize: 15,
    lineHeight: 19,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
  },
  statusStripBody: {
    color: '#c9c6bf',
    fontSize: 13,
    lineHeight: 19,
    fontFamily: 'Inter_400Regular',
  },
  statusStripMeta: {
    color: '#8e8b84',
    fontSize: 11,
    lineHeight: 16,
    fontFamily: 'Inter_400Regular',
  },
  statePanel: {
    borderWidth: 1,
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 10,
  },
  statePanelToneSage: {
    backgroundColor: 'rgba(138, 154, 91, 0.08)',
    borderColor: 'rgba(138, 154, 91, 0.24)',
  },
  statePanelToneClay: {
    backgroundColor: 'rgba(165, 113, 100, 0.08)',
    borderColor: 'rgba(165, 113, 100, 0.24)',
  },
  statePanelEyebrow: {
    color: '#8e8b84',
    fontSize: 10,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '700',
    letterSpacing: 1.1,
    textTransform: 'uppercase',
  },
  statePanelTitle: {
    color: '#E5E4E2',
    fontSize: 18,
    lineHeight: 22,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
  },
  statePanelBody: {
    color: '#c9c6bf',
    fontSize: 13,
    lineHeight: 20,
    fontFamily: 'Inter_400Regular',
  },
  statePanelMeta: {
    color: '#8e8b84',
    fontSize: 11,
    lineHeight: 16,
    fontFamily: 'Inter_400Regular',
  },
  statePanelSkeletonStack: {
    marginTop: 2,
    gap: 8,
  },
  statePanelSkeletonWide: {
    width: '100%',
    height: 10,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
  },
  statePanelSkeletonMid: {
    width: '76%',
    height: 10,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
  },
  statePanelSkeletonShort: {
    width: '48%',
    height: 10,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
  },
  collapsibleHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  collapsibleHeaderPressed: {
    opacity: 0.88,
    transform: [{ scale: 0.992 }],
  },
  collapsibleHeaderContent: {
    flex: 1,
    gap: 4,
  },
  collapsibleTitle: {
    color: '#E5E4E2',
    fontSize: 16,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
  },
  collapsibleMeta: {
    color: '#8e8b84',
    fontSize: 11,
    fontFamily: 'Inter_500Medium',
  },
  collapsibleChevron: {
    color: '#8A9A5B',
    fontSize: 18,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
  },
  collapsibleBodyWrap: {
    overflow: 'hidden',
  },
  collapsibleBodyInner: {
    paddingTop: 10,
    gap: 10,
  },
  screenTitle: {
    color: '#E5E4E2',
    fontSize: 19,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
  },
  screenBody: {
    color: '#c9c6bf',
    fontSize: 14,
    fontFamily: 'Inter_400Regular',
    lineHeight: 21,
  },
  screenMeta: {
    color: '#8e8b84',
    fontSize: 12,
    fontFamily: 'Inter_400Regular',
  },
  movieList: {
    marginTop: 8,
    gap: 8,
  },
  movieRow: {
    padding: 12,
    backgroundColor: 'rgba(31, 31, 31, 0.7)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    gap: 2,
  },
  movieRowPressed: {
    backgroundColor: 'rgba(138, 154, 91, 0.12)',
    borderColor: 'rgba(138, 154, 91, 0.34)',
    transform: [{ scale: 0.988 }],
  },
  movieTitle: {
    color: '#E5E4E2',
    fontSize: 14,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  movieMeta: {
    marginTop: 4,
    color: '#8e8b84',
    fontSize: 12,
    fontFamily: 'Inter_400Regular',
  },
  movieRowActionHint: {
    marginTop: 8,
    color: '#8A9A5B',
    fontSize: 11,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  inboxList: {
    marginTop: 6,
  },
  inboxItemSeparator: {
    height: 8,
  },
  inboxRow: {
    backgroundColor: 'rgba(31, 31, 31, 0.7)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 6,
  },
  inboxTitle: {
    color: '#E5E4E2',
    fontSize: 12,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '700',
  },
  inboxTitleState: {
    color: '#8e8b84',
    fontSize: 11,
    fontFamily: 'Inter_500Medium',
    fontWeight: '600',
  },
  inboxMeta: {
    color: '#8e8b84',
    fontSize: 11,
    fontFamily: 'Inter_400Regular',
  },
  inboxBody: {
    color: '#E5E4E2',
    fontSize: 12,
    fontFamily: 'Inter_400Regular',
  },
  inboxHighlight: {
    backgroundColor: 'rgba(138, 154, 91, 0.24)',
    color: '#E5E4E2',
    borderRadius: 4,
    overflow: 'hidden',
  },
  inboxOpenButton: {
    marginTop: 4,
    alignSelf: 'flex-start',
    backgroundColor: '#8A9A5B',
    borderRadius: 12,
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 10,
    justifyContent: 'center',
  },
  inboxActionRow: {
    marginTop: 4,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  inboxCopyButton: {
    marginTop: 4,
    alignSelf: 'flex-start',
    backgroundColor: '#A57164',
    borderRadius: 12,
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 10,
    justifyContent: 'center',
  },
  inboxBulkOpenButton: {
    marginTop: 4,
    alignSelf: 'flex-start',
    backgroundColor: '#8A9A5B',
    borderRadius: 12,
    minHeight: 44,
    paddingHorizontal: 14,
    paddingVertical: 10,
    justifyContent: 'center',
  },
  inboxBulkRemoveButton: {
    marginTop: 4,
    alignSelf: 'flex-start',
    backgroundColor: '#7f1d1d',
    borderRadius: 12,
    minHeight: 44,
    paddingHorizontal: 14,
    paddingVertical: 10,
    justifyContent: 'center',
  },
  inboxFilterRow: {
    marginTop: 6,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  inboxSearchInput: {
    marginTop: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderRadius: 12,
    color: '#E5E4E2',
    fontSize: 13,
    fontFamily: 'Inter_400Regular',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  inboxSortRow: {
    marginTop: 6,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  inboxPaginationRow: {
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  inboxPageButton: {
    backgroundColor: '#8A9A5B',
    borderRadius: 8,
    minHeight: 44,
    paddingHorizontal: 10,
    paddingVertical: 6,
    justifyContent: 'center',
  },
  inboxPaginationText: {
    color: '#E5E4E2',
    fontSize: 12,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  ritualInput: {
    minHeight: 100,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderRadius: 14,
    color: '#E5E4E2',
    fontSize: 14,
    fontFamily: 'Inter_400Regular',
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  ritualMetaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  ritualStateOk: {
    color: '#8A9A5B',
  },
  ritualStateWarn: {
    color: '#A57164',
  },
  ritualStateError: {
    color: '#fca5a5',
  },
  ritualActionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  profileGrid: {
    marginTop: 6,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  profileMetricCard: {
    minWidth: 90,
    flexGrow: 1,
    backgroundColor: 'rgba(31, 31, 31, 0.7)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 4,
  },
  profileMetricValue: {
    color: '#E5E4E2',
    fontSize: 16,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
  },
  profileMetricLabel: {
    color: '#8e8b84',
    fontSize: 11,
    fontFamily: 'Inter_500Medium',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  profileXpSummaryRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  profileXpSummaryBlock: {
    flex: 1,
    gap: 4,
  },
  profileXpSummaryBlockRight: {
    alignItems: 'flex-end',
  },
  profileXpSummaryLabel: {
    color: '#8e8b84',
    fontSize: 10,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '700',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  profileXpSummaryValue: {
    color: '#E5E4E2',
    fontSize: 18,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
  },
  profileXpTrack: {
    height: 14,
    borderRadius: 999,
    overflow: 'hidden',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  profileXpFill: {
    position: 'relative',
    height: '100%',
    borderRadius: 999,
    overflow: 'hidden',
  },
  profileXpFillHeadTint: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    width: '62%',
    opacity: 0.92,
  },
  profileXpFillSpark: {
    position: 'absolute',
    top: 1,
    bottom: 1,
    right: 0,
    width: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 255, 255, 0.58)',
  },
  profileXpScaleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  profileXpScaleText: {
    color: '#8e8b84',
    fontSize: 11,
    fontFamily: 'Inter_500Medium',
  },
  badgeRow: {
    marginTop: 4,
    gap: 2,
  },
  warningBox: {
    marginTop: 12,
    backgroundColor: 'rgba(165, 113, 100, 0.08)',
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: 'rgba(165, 113, 100, 0.3)',
    padding: 12,
  },
  warningText: {
    color: '#E5E4E2',
    fontSize: 13,
    fontFamily: 'Inter_400Regular',
    lineHeight: 20,
  },
  exploreRouteList: {
    marginTop: 6,
    gap: 10,
  },
  exploreRouteRow: {
    backgroundColor: 'rgba(31, 31, 31, 0.7)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderRadius: 16,
    padding: 14,
    gap: 12,
  },
  exploreRouteContent: {
    gap: 4,
  },
  exploreRouteTitle: {
    color: '#E5E4E2',
    fontSize: 13,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  exploreRouteBody: {
    color: '#8e8b84',
    fontSize: 12,
    fontFamily: 'Inter_400Regular',
    lineHeight: 18,
  },
  exploreRouteAction: {
    alignSelf: 'flex-start',
  },
  arenaMetricGrid: {
    marginTop: 6,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  arenaMetricCard: {
    minWidth: 92,
    flexGrow: 1,
    backgroundColor: 'rgba(31, 31, 31, 0.7)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 4,
  },
  arenaMetricValue: {
    color: '#E5E4E2',
    fontSize: 15,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
  },
  arenaMetricLabel: {
    color: '#8e8b84',
    fontSize: 10,
    fontFamily: 'Inter_500Medium',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  arenaLeaderboardList: {
    marginTop: 4,
    gap: 8,
  },
  arenaLeaderboardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: 'rgba(31, 31, 31, 0.7)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  arenaLeaderboardRankWrap: {
    width: 24,
    height: 24,
    borderRadius: 999,
    backgroundColor: 'rgba(138, 154, 91, 0.18)',
    borderColor: '#8A9A5B',
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  arenaLeaderboardRank: {
    color: '#E5E4E2',
    fontSize: 11,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
  },
  arenaLeaderboardContent: {
    flex: 1,
    gap: 2,
  },
  arenaLeaderboardName: {
    color: '#E5E4E2',
    fontSize: 12,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  arenaLeaderboardMeta: {
    color: '#8e8b84',
    fontSize: 11,
    fontFamily: 'Inter_400Regular',
  },
  arenaLeaderboardAction: {
    minWidth: 74,
  },
  publicProfileInput: {
    marginTop: 2,
    backgroundColor: '#141414',
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderWidth: 1,
    borderRadius: 10,
    color: '#E5E4E2',
    fontSize: 12,
    fontFamily: 'Inter_400Regular',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  rulesList: {
    marginTop: 4,
    gap: 8,
  },
  rulesRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  rulesDot: {
    marginTop: 7,
    width: 5,
    height: 5,
    borderRadius: 999,
    backgroundColor: '#8A9A5B',
  },
  rulesText: {
    flex: 1,
    color: '#c9c6bf',
    fontSize: 12,
    lineHeight: 18,
    fontFamily: 'Inter_400Regular',
  },
  actionsRow: {
    flexDirection: 'row',
    gap: 10,
    backgroundColor: '#1f1f1f',
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderWidth: 1,
    borderRadius: 14,
    padding: 10,
  },
  actionsHint: {
    marginTop: -6,
    paddingHorizontal: 4,
    color: '#8e8b84',
    fontSize: 11,
    fontFamily: 'Inter_500Medium',
  },
  singleActionRow: {
    backgroundColor: '#1f1f1f',
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderWidth: 1,
    borderRadius: 14,
    padding: 10,
  },
  sectionHeaderRow: {
    marginTop: 4,
    marginBottom: 0,
    paddingHorizontal: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  sectionAnchor: {
    marginTop: 2,
  },
  quickNavRow: {
    marginTop: 2,
    flexDirection: 'row',
    gap: 8,
    backgroundColor: '#171717',
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderWidth: 1,
    borderRadius: 12,
    padding: 8,
  },
  quickNavHint: {
    marginTop: -4,
    paddingHorizontal: 4,
    color: '#8e8b84',
    fontSize: 11,
    fontFamily: 'Inter_500Medium',
  },
  backToTopWrap: {
    position: 'absolute',
    right: 14,
    bottom: 22,
    width: 110,
    gap: 8,
  },
  backToTopMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#171717',
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  backToTopMetaKey: {
    color: '#8e8b84',
    fontSize: 10,
    fontFamily: 'Inter_500Medium',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  backToTopMetaValue: {
    color: '#E5E4E2',
    fontSize: 10,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  backToTopQuickRow: {
    flexDirection: 'row',
    gap: 8,
  },
  sectionHeader: {
    color: '#E5E4E2',
    fontSize: 11,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
    letterSpacing: 0.9,
    textTransform: 'uppercase',
  },
  sectionHeaderMeta: {
    color: '#8e8b84',
    fontSize: 11,
    fontFamily: 'Inter_500Medium',
  },
  subSectionLabel: {
    marginTop: 2,
    color: '#8e8b84',
    fontSize: 10,
    fontFamily: 'Inter_600SemiBold',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  retryButton: {
    marginTop: 8,
    alignSelf: 'flex-start',
    backgroundColor: '#8A9A5B',
    borderRadius: 999,
    minHeight: 48,
    paddingHorizontal: 20,
    paddingVertical: 12,
    justifyContent: 'center',
    ...buildViewShadow({ color: '#8A9A5B', opacity: 0.15, radius: 10, offsetY: 4, elevation: 4 }),
  },
  retryText: {
    color: '#E5E4E2',
    fontSize: 12,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  authForm: {
    marginTop: 8,
    gap: 8,
  },
  authModeSurface: {
    backgroundColor: 'rgba(255, 255, 255, 0.035)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderRadius: 16,
    padding: 14,
    gap: 10,
  },
  authFieldStack: {
    gap: 8,
  },
  authActionStack: {
    gap: 10,
  },
  authSubtleAction: {
    color: '#8A9A5B',
    fontSize: 12,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  authRecoveryLabel: {
    color: '#c9c6bf',
    fontSize: 12,
    lineHeight: 18,
    fontFamily: 'Inter_400Regular',
  },
  authRememberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  authRememberRowPressed: {
    opacity: 0.86,
  },
  authRememberCheckbox: {
    width: 22,
    height: 22,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  authRememberCheckboxActive: {
    borderColor: '#8A9A5B',
    backgroundColor: '#8A9A5B',
  },
  authRememberCopy: {
    flex: 1,
    gap: 2,
  },
  authRememberLabel: {
    color: '#E5E4E2',
    fontSize: 13,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  authRememberMeta: {
    color: '#8e8b84',
    fontSize: 11,
    lineHeight: 16,
    fontFamily: 'Inter_400Regular',
  },
  authDividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 2,
  },
  authDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
  },
  authDividerText: {
    color: '#8e8b84',
    fontSize: 10,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
    letterSpacing: 0.8,
  },
  authProviderButton: {
    minHeight: 52,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  authProviderButtonPressed: {
    opacity: 0.88,
    transform: [{ scale: 0.98 }],
  },
  authProviderButtonDisabled: {
    opacity: 0.55,
  },
  authProviderIconWrap: {
    width: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  authProviderButtonText: {
    color: '#E5E4E2',
    fontSize: 13,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  authProviderLogoButton: {
    minHeight: 64,
    borderRadius: 20,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    ...buildViewShadow({ color: '#121212', opacity: 0.18, radius: 12, offsetY: 4, elevation: 3 }),
  },
  authProviderLogoButtonLight: {
    borderColor: 'rgba(255, 255, 255, 0.18)',
    backgroundColor: '#f4f1ea',
  },
  authProviderLogoButtonDark: {
    borderColor: 'rgba(255, 255, 255, 0.12)',
    backgroundColor: '#171717',
  },
  authProviderLogoButtonPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.98 }],
  },
  authProviderLogoButtonDisabled: {
    opacity: 0.55,
  },
  authProviderLogoIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  authProviderHintText: {
    color: '#8e8b84',
    fontSize: 11,
    lineHeight: 17,
    fontFamily: 'Inter_400Regular',
    textAlign: 'center',
  },
  authAppleButton: {
    width: '100%',
    height: 48,
  },
  authAppleButtonDisabled: {
    opacity: 0.62,
  },
  authSignedInBox: {
    marginTop: 8,
    gap: 8,
  },
  authLaunchScreen: {
    flex: 1,
    backgroundColor: '#121212',
  },
  authLaunchScroll: {
    paddingHorizontal: 20,
    paddingTop: 54,
    paddingBottom: 32,
    gap: 18,
  },
  authLaunchTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  authLaunchChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  authLaunchChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(138, 154, 91, 0.28)',
    backgroundColor: 'rgba(138, 154, 91, 0.12)',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  authLaunchChipText: {
    color: '#E5E4E2',
    fontSize: 10,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
    letterSpacing: 0.7,
    textTransform: 'uppercase',
  },
  authLaunchHero: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    backgroundColor: '#171717',
    paddingHorizontal: 20,
    paddingVertical: 22,
    gap: 8,
  },
  authLaunchBrand: {
    color: '#8A9A5B',
    fontSize: 52,
    lineHeight: 56,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
    letterSpacing: -2,
  },
  authLaunchEyebrow: {
    color: '#c9c6bf',
    fontSize: 11,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
    letterSpacing: 2.1,
  },
  authLaunchTitle: {
    color: '#E5E4E2',
    fontSize: 22,
    lineHeight: 29,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
  },
  authLaunchBody: {
    color: '#c9c6bf',
    fontSize: 13,
    lineHeight: 20,
    fontFamily: 'Inter_400Regular',
  },
  authGateScreen: {
    flex: 1,
  },
  authGateScroll: {
    paddingHorizontal: 20,
    paddingTop: 56,
    paddingBottom: 48,
    gap: 18,
  },
  authGateHero: {
    borderRadius: 32,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    backgroundColor: 'rgba(17, 17, 17, 0.94)',
    paddingHorizontal: 24,
    paddingVertical: 26,
    gap: 12,
    ...buildViewShadow({ color: '#121212', opacity: 0.42, radius: 20, offsetY: 10, elevation: 8 }),
  },
  authGateBrand: {
    color: '#E5E4E2',
    fontSize: 64,
    lineHeight: 64,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
    letterSpacing: -3,
  },
  authGateEyebrow: {
    color: '#A57164',
    fontSize: 11,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '700',
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  authGateTitle: {
    color: '#E5E4E2',
    fontSize: 28,
    lineHeight: 34,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
  },
  authGateBody: {
    color: '#c9c6bf',
    fontSize: 14,
    lineHeight: 22,
    fontFamily: 'Inter_400Regular',
  },
  authGateFeatureList: {
    gap: 10,
  },
  authGateFeatureRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  authGateFeatureDot: {
    marginTop: 6,
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: '#8A9A5B',
  },
  authGateFeatureText: {
    flex: 1,
    color: '#E5E4E2',
    fontSize: 13,
    lineHeight: 19,
    fontFamily: 'Inter_500Medium',
  },
  authGateStartButton: {
    marginTop: 4,
  },
  detailInfoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  detailInfoCard: {
    minWidth: 108,
    flexGrow: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.035)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 4,
  },
  detailInfoLabel: {
    color: '#8e8b84',
    fontSize: 10,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '700',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  detailInfoValue: {
    color: '#E5E4E2',
    fontSize: 12,
    lineHeight: 17,
    fontFamily: 'Inter_500Medium',
  },
  input: {
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderRadius: 14,
    color: '#E5E4E2',
    fontSize: 14,
    fontFamily: 'Inter_400Regular',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  claimButton: {
    marginTop: 6,
    alignSelf: 'flex-start',
    backgroundColor: '#8A9A5B',
    borderRadius: 999,
    minHeight: 48,
    paddingHorizontal: 24,
    paddingVertical: 12,
    justifyContent: 'center',
    ...buildViewShadow({ color: '#8A9A5B', opacity: 0.2, radius: 14, offsetY: 4, elevation: 5 }),
  },
  claimButtonDisabled: {
    opacity: 0.7,
  },
  claimButtonText: {
    color: '#E5E4E2',
    fontSize: 12,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  signOutButton: {
    alignSelf: 'flex-start',
    backgroundColor: '#7f1d1d',
    borderRadius: 999,
    minHeight: 48,
    paddingHorizontal: 20,
    paddingVertical: 12,
    justifyContent: 'center',
  },
  claimSuccess: {
    marginTop: 6,
    padding: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#8A9A5B',
    backgroundColor: 'rgba(138, 154, 91, 0.14)',
    gap: 2,
  },
  claimSuccessText: {
    color: '#d9e2bf',
    fontSize: 12,
    fontFamily: 'Inter_500Medium',
    fontWeight: '600',
  },
  claimError: {
    marginTop: 6,
    padding: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#7f1d1d',
    backgroundColor: 'rgba(127, 29, 29, 0.24)',
    gap: 2,
  },
  claimErrorText: {
    color: '#fecaca',
    fontSize: 12,
    fontFamily: 'Inter_500Medium',
    fontWeight: '600',
  },
  card: {
    backgroundColor: 'rgba(31, 31, 31, 0.7)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
    gap: 12,
  },
  leagueTransitionOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.72)',
    paddingHorizontal: 20,
  },
  leagueTransitionOverlayTap: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  leagueTransitionCard: {
    width: '100%',
    maxWidth: 420,
    borderWidth: 1,
    borderRadius: 24,
    backgroundColor: 'rgba(17, 17, 17, 0.95)',
    paddingHorizontal: 22,
    paddingVertical: 20,
    alignItems: 'center',
    ...buildViewShadow({ color: '#121212', opacity: 0.35, radius: 20, offsetY: 12, elevation: 16 }),
  },
  leagueTransitionLine: {
    width: 84,
    height: 2,
    borderRadius: 999,
    marginBottom: 16,
  },
  leagueTransitionEyebrow: {
    color: 'rgba(229, 228, 226, 0.62)',
    fontSize: 10,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
    letterSpacing: 2.2,
    textTransform: 'uppercase',
  },
  leagueTransitionLeagueName: {
    marginTop: 8,
    fontSize: 34,
    lineHeight: 40,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1.8,
    textAlign: 'center',
  },
  leagueTransitionBody: {
    marginTop: 12,
    color: '#E5E4E2',
    fontSize: 13,
    lineHeight: 20,
    fontFamily: 'Inter_500Medium',
    textAlign: 'center',
  },
  leagueTransitionMeta: {
    marginTop: 8,
    color: 'rgba(229, 228, 226, 0.62)',
    fontSize: 10,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
    letterSpacing: 1.3,
    textTransform: 'uppercase',
  },
  leagueTransitionButton: {
    marginTop: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 999,
    minHeight: 44,
    paddingHorizontal: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  leagueTransitionButtonText: {
    color: '#E5E4E2',
    fontSize: 11,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  cardTitle: {
    color: '#E5E4E2',
    fontSize: 14,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  code: {
    color: '#c9c6bf',
    fontFamily: 'monospace',
    fontSize: 12,
    lineHeight: 18,
  },
  /* Theme Mode Classes (Dawn support & Glassmorphic Toggle) */
  safeAreaDawn: {
    backgroundColor: '#171717',
  },
  backdropLayerDawn: {
    backgroundColor: '#e5e4e2',
  },
  navSceneDawn: {
    backgroundColor: '#e5e4e2',
  },
  navTabBarDawn: {
    backgroundColor: 'rgba(250, 249, 246, 0.95)',
    borderColor: 'rgba(0, 0, 0, 0.08)',
  },
  themeModeSegmentContainer: {
    marginTop: 8,
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderRadius: 12,
    padding: 6,
    gap: 6,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
  },
  themeModeSegmentOption: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: 'transparent',
  },
  themeModeSegmentActiveMidnight: {
    backgroundColor: 'rgba(31, 31, 31, 0.9)',
    ...buildViewShadow({ color: '#121212', opacity: 0.3, radius: 8, offsetY: 4, elevation: 4 }),
    borderColor: '#8A9A5B',
    borderWidth: 1,
  },
  themeModeSegmentActiveDawn: {
    backgroundColor: 'rgba(165, 113, 100, 0.9)', // Clay accent for Dawn
    ...buildViewShadow({ color: '#121212', opacity: 0.4, radius: 8, offsetY: 4, elevation: 4 }),
    borderColor: 'rgba(255, 255, 255, 0.4)',
    borderWidth: 1,
  },
  themeModeSegmentText: {
    color: '#8e8b84',
    fontSize: 13,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  themeModeSegmentTextActiveMidnight: {
    color: '#E5E4E2',
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
  },
  themeModeSegmentTextActiveDawn: {
    color: '#e5e4e2',
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
  },

  /* Comment Feed Classes */
  commentFeedFilterStack: {
    marginTop: 6,
    gap: 6,
  },
  commentFeedControlRow: {
    flexDirection: 'row',
    flexWrap: 'nowrap',
    backgroundColor: 'rgba(255, 255, 255, 0.025)',
    borderRadius: 12,
    padding: 4,
    gap: 4,
    borderWidth: 0,
    borderColor: 'transparent',
  },
  commentFeedFilterRow: {
    marginTop: 10,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  commentFeedSearchInput: {
    marginTop: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderWidth: 1,
    borderRadius: 16,
    color: '#E5E4E2',
    fontSize: 14,
    fontFamily: 'Inter_400Regular',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  commentFeedList: {
    marginTop: 12,
    gap: 12,
  },
  commentFeedRow: {
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
    backgroundColor: 'rgba(31, 31, 31, 0.5)',
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 8,
  },
  commentFeedRowHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  commentFeedMovieTitle: {
    flex: 1,
    color: '#E5E4E2',
    fontSize: 13,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  commentFeedMineBadge: {
    color: '#E5E4E2',
    fontSize: 9,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
    letterSpacing: 0.5,
    backgroundColor: 'rgba(138, 154, 91, 0.24)',
    borderColor: '#8A9A5B',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 7,
    paddingVertical: 2,
    overflow: 'hidden',
    textTransform: 'uppercase',
  },
  commentFeedMeta: {
    color: '#8e8b84',
    fontSize: 11,
    fontFamily: 'Inter_500Medium',
  },
  commentFeedAuthorMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  commentFeedAvatarWrap: {
    width: 22,
    height: 22,
    borderRadius: 999,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    backgroundColor: 'rgba(138, 154, 91, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  commentFeedAvatarImage: {
    width: '100%',
    height: '100%',
  },
  commentFeedAvatarFallback: {
    color: '#E5E4E2',
    fontSize: 10,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
  },
  commentFeedAuthorLink: {
    color: '#8A9A5B',
    fontSize: 11,
    fontFamily: 'Inter_600SemiBold',
    textDecorationLine: 'underline',
  },
  commentFeedLeagueBadge: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 7,
    paddingVertical: 2,
    marginLeft: 2,
  },
  commentFeedLeagueBadgeText: {
    fontSize: 9,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  commentFeedBody: {
    color: '#E5E4E2',
    fontSize: 13,
    fontFamily: 'Inter_400Regular',
    lineHeight: 20,
    marginTop: 2,
    marginBottom: 4,
  },
  commentFeedActionRow: {
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.04)',
    paddingTop: 8,
  },
  commentFeedInlineActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  commentFeedInlineAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 4,
  },
  commentFeedInlineActionActive: {
    opacity: 1,
  },
  commentFeedInlineActionText: {
    color: '#C9C6BF',
    fontSize: 10,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  commentFeedInlineActionTextActive: {
    color: '#E5E4E2',
  },
  commentFeedInlineActionDanger: {
    opacity: 0.92,
  },
  commentFeedInlineActionDangerText: {
    color: '#A57164',
  },
  commentFeedActionButton: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
  },
  commentFeedActionButtonActive: {
    borderColor: '#8A9A5B',
    backgroundColor: 'rgba(138, 154, 91, 0.18)',
  },
  commentFeedActionButtonText: {
    color: '#C9C6BF',
    fontSize: 10,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  commentFeedActionButtonTextActive: {
    color: '#E5E4E2',
  },
  commentFeedRowStatus: {
    marginTop: 8,
    fontSize: 11,
    fontFamily: 'Inter_500Medium',
  },
  commentFeedReplyPanel: {
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.05)',
    paddingTop: 10,
    gap: 10,
  },
  commentFeedReplyList: {
    gap: 8,
  },
  commentFeedReplyRow: {
    backgroundColor: 'rgba(255, 255, 255, 0.035)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 6,
  },
  commentFeedReplyHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  commentFeedReplyAuthor: {
    color: '#E5E4E2',
    fontSize: 11,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  commentFeedReplyText: {
    color: '#E5E4E2',
    fontSize: 12,
    lineHeight: 18,
    fontFamily: 'Inter_400Regular',
  },
  commentFeedReplyComposer: {
    gap: 8,
  },
  commentFeedReplyInput: {
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderRadius: 14,
    color: '#E5E4E2',
    fontSize: 13,
    lineHeight: 18,
    fontFamily: 'Inter_400Regular',
    paddingHorizontal: 14,
    paddingVertical: 12,
    minHeight: 84,
    textAlignVertical: 'top',
  },
  commentFeedReplySendButton: {
    alignSelf: 'flex-start',
    backgroundColor: '#A45E4A',
    borderRadius: 999,
    minHeight: 40,
    paddingHorizontal: 18,
    paddingVertical: 10,
    justifyContent: 'center',
  },
  commentFeedReplySendButtonText: {
    color: '#E5E4E2',
    fontSize: 11,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  commentFeedActionText: {
    color: '#8A9A5B',
    fontSize: 11,
    fontFamily: 'Inter_600SemiBold',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  commentFeedSegmentContainer: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderRadius: 12,
    padding: 4,
    gap: 4,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
  },
  commentFeedSegmentOption: {
    flex: 1,
    minWidth: 0,
    paddingHorizontal: 8,
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: 'transparent',
  },
  commentFeedSegmentActive: {
    backgroundColor: 'rgba(138, 154, 91, 0.2)',
    borderColor: '#8A9A5B',
    borderWidth: 1,
  },
  commentFeedSegmentText: {
    color: '#8e8b84',
    fontSize: 11,
    fontFamily: 'Inter_500Medium',
    textAlign: 'center',
  },
  commentFeedSegmentTextActive: {
    color: '#E5E4E2',
    fontFamily: 'Inter_600SemiBold',
  },
  commentFeedBottomActionRow: {
    marginTop: 8,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  commentFeedBottomActionButton: {
    marginTop: 0,
    alignSelf: 'auto',
    flexGrow: 1,
    minWidth: 148,
    alignItems: 'center',
  },

  /* Profile Mark Classes */
  markPillRow: {
    marginTop: 8,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  markCategoryList: {
    gap: 12,
  },
  markCategoryBlock: {
    gap: 8,
  },
  markCategoryTitle: {
    color: '#8e8b84',
    fontSize: 11,
    fontFamily: 'Inter_600SemiBold',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  markPill: {
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    backgroundColor: 'rgba(45, 45, 45, 0.6)',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  markPillContentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  markPillGlyph: {
    width: 8,
    height: 8,
    borderRadius: 999,
  },
  markPillGlyphUnlocked: {
    backgroundColor: '#8A9A5B',
  },
  markPillGlyphLocked: {
    backgroundColor: 'rgba(142, 139, 132, 0.62)',
  },
  markPillGlyphFeatured: {
    backgroundColor: '#d9e2bf',
    ...buildViewShadow({ color: '#8A9A5B', opacity: 0.5, radius: 8, offsetY: 0, elevation: 4 }),
  },
  markPillText: {
    color: '#E5E4E2',
    fontSize: 12,
    fontFamily: 'Inter_500Medium',
  },
  markPillFeatured: {
    borderWidth: 1,
    borderColor: '#8A9A5B',
    backgroundColor: 'rgba(138, 154, 91, 0.18)',
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 8,
    ...buildViewShadow({ color: '#8A9A5B', opacity: 0.4, radius: 12, offsetY: 4, elevation: 6 }),
  },
  markPillFeaturedText: {
    color: '#d9e2bf',
    fontSize: 13,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
    ...buildTextShadow({ color: 'rgba(138, 154, 91, 0.4)', radius: 8 }),
  },

  /* Daily Features Classes */
  dailyDataSourceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  dataSourceBadgeLive: {
    backgroundColor: 'rgba(138, 154, 91, 0.15)',
    borderWidth: 1,
    borderColor: 'rgba(138, 154, 91, 0.4)',
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 4,
  },
  dataSourceTextLive: {
    color: '#8A9A5B',
    fontSize: 10,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  dataSourceBadgeFallback: {
    backgroundColor: 'rgba(165, 113, 100, 0.15)',
    borderWidth: 1,
    borderColor: 'rgba(165, 113, 100, 0.4)',
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 4,
  },
  dataSourceTextFallback: {
    color: '#A57164',
    fontSize: 10,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  errorBox: {
    marginTop: 12,
    marginBottom: 8,
    backgroundColor: 'rgba(127, 29, 29, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(127, 29, 29, 0.3)',
    padding: 16,
    borderRadius: 6,
  },
  errorText: {
    color: '#E5E4E2',
    fontSize: 13,
    fontFamily: 'Inter_500Medium',
    lineHeight: 20,
  },
  cycleTimeContainer: {
    alignItems: 'flex-start',
    gap: 6,
    marginBottom: 12,
  },
  cycleTimeLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  cycleTimeTextMode: {
    color: '#8A9A5B',
    fontSize: 10,
    fontFamily: 'Inter_700Bold',
    letterSpacing: 1.4,
    textTransform: 'uppercase',
  },
  cycleTimeTextTime: {
    color: '#E5E4E2',
    fontSize: 12,
    fontFamily: 'Inter_600SemiBold',
  },
  cycleTimeBarTrack: {
    width: '100%',
    height: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    overflow: 'hidden',
  },
  cycleTimeBarFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#8A9A5B',
  },
  movieListHorizontal: {
    marginTop: 14,
    paddingBottom: 4,
    paddingRight: 4,
  },
  movieListHorizontalSpacer: {
    width: 12,
  },
  movieCardWrapper: {
    width: 132,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    overflow: 'hidden',
  },
  movieCardWrapperSelected: {
    borderColor: 'rgba(138, 154, 91, 0.7)',
    backgroundColor: 'rgba(138, 154, 91, 0.12)',
  },
  movieCardPoster: {
    width: '100%',
    height: 182,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(20, 20, 20, 0.9)',
  },
  movieCardPosterImage: {
    width: '100%',
    height: '100%',
  },
  movieCardPosterFallbackLabel: {
    color: '#E5E4E2',
    fontSize: 24,
    fontFamily: 'Inter_700Bold',
    opacity: 0.25,
  },
  movieCardContentWrapper: {
    paddingHorizontal: 10,
    paddingVertical: 10,
    gap: 4,
  },
  movieCardTitleLabel: {
    color: '#E5E4E2',
    fontSize: 13,
    fontFamily: 'Inter_600SemiBold',
    lineHeight: 18,
  },
  movieCardMetaLabel: {
    color: '#8e8b84',
    fontSize: 11,
    fontFamily: 'Inter_400Regular',
  },
  modalOverlaySurface: {
    flex: 1,
    backgroundColor: 'rgba(18, 18, 18, 0.94)',
    justifyContent: 'flex-end',
  },
  modalSheetSurface: {
    maxHeight: '92%',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderTopWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    backgroundColor: '#171717',
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 20,
    gap: 10,
  },
  modalSheetScroll: {
    gap: 10,
    paddingBottom: 8,
  },
  modalNavRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  modalCloseTextBtn: {
    color: '#E5E4E2',
    fontSize: 14,
    fontFamily: 'Inter_600SemiBold',
  },
  modalContentSurface: {
    gap: 10,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    padding: 14,
  },
  movieDetailPoster: {
    width: '100%',
    height: 212,
    borderRadius: 12,
  },
  movieDetailTitle: {
    color: '#E5E4E2',
    fontSize: 22,
    fontFamily: 'Inter_700Bold',
    lineHeight: 28,
  },
  movieDetailMeta: {
    color: '#A57164',
    fontSize: 12,
    fontFamily: 'Inter_500Medium',
  },
  movieDetailBody: {
    color: '#c9c6bf',
    fontSize: 14,
    fontFamily: 'Inter_400Regular',
    lineHeight: 22,
  },
  movieDetailCast: {
    color: '#8e8b84',
    fontSize: 12,
    fontFamily: 'Inter_400Regular',
    lineHeight: 18,
  },
  movieArchiveHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 14,
  },
  movieArchivePoster: {
    width: 88,
    height: 128,
    borderRadius: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
  },
  movieArchivePosterFallback: {
    width: 88,
    height: 128,
    borderRadius: 14,
    backgroundColor: 'rgba(138, 154, 91, 0.14)',
    borderColor: 'rgba(138, 154, 91, 0.3)',
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  movieArchivePosterFallbackText: {
    color: '#E5E4E2',
    fontSize: 18,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
    letterSpacing: 1.2,
  },
  movieArchiveHeaderContent: {
    flex: 1,
    gap: 8,
  },
  movieArchiveBadgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  movieArchiveBadge: {
    borderWidth: 1,
    borderColor: 'rgba(138, 154, 91, 0.28)',
    backgroundColor: 'rgba(138, 154, 91, 0.12)',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  movieArchiveBadgeText: {
    color: '#d9e2bf',
    fontSize: 10,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  movieArchiveEntryList: {
    gap: 10,
  },
  movieArchiveEntryCard: {
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
    backgroundColor: 'rgba(31, 31, 31, 0.5)',
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 8,
  },
  movieArchiveEntryHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 8,
  },
  movieArchiveEntryDate: {
    color: '#E5E4E2',
    fontSize: 11,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  movieArchiveEntryGenre: {
    color: '#8A9A5B',
    fontSize: 10,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  movieArchiveEntryBody: {
    color: '#E5E4E2',
    fontSize: 13,
    lineHeight: 20,
    fontFamily: 'Inter_400Regular',
    fontStyle: 'italic',
  },
  movieArchiveRepliesLabel: {
    color: '#8A9A5B',
    fontSize: 10,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  movieArchiveDeleteText: {
    color: '#A57164',
    fontSize: 10,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  modalActionStack: {
    marginTop: 6,
    gap: 8,
  },
  dailyQuizPanel: {
    marginTop: 18,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.06)',
    gap: 12,
  },
  dailyQuizHeader: {
    gap: 6,
  },
  dailyQuizEyebrow: {
    color: '#8A9A5B',
    fontSize: 10,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
    letterSpacing: 1.4,
    textTransform: 'uppercase',
  },
  dailyQuizSubtitle: {
    color: '#c9c6bf',
    fontSize: 13,
    lineHeight: 20,
    fontFamily: 'Inter_400Regular',
  },
  dailyQuizStack: {
    gap: 12,
  },
  dailyQuizSummaryCard: {
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
    backgroundColor: 'rgba(15, 15, 15, 0.86)',
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 6,
  },
  dailyQuizSummaryText: {
    color: '#8e8b84',
    fontSize: 11,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  dailyQuizQuestionCard: {
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
    backgroundColor: '#111111',
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 12,
  },
  dailyQuizQuestionText: {
    color: '#F4F1E8',
    fontSize: 15,
    lineHeight: 22,
    fontFamily: 'Inter_500Medium',
  },
  dailyQuizOptionList: {
    gap: 8,
  },
  dailyQuizOptionButton: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    backgroundColor: '#181818',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  dailyQuizOptionPressed: {
    opacity: 0.86,
  },
  dailyQuizOptionSelected: {
    borderColor: 'rgba(138, 154, 91, 0.45)',
    backgroundColor: 'rgba(138, 154, 91, 0.12)',
  },
  dailyQuizOptionCorrect: {
    borderColor: 'rgba(52, 211, 153, 0.5)',
    backgroundColor: 'rgba(16, 185, 129, 0.16)',
  },
  dailyQuizOptionWrong: {
    borderColor: 'rgba(248, 113, 113, 0.45)',
    backgroundColor: 'rgba(239, 68, 68, 0.12)',
  },
  dailyQuizOptionDisabled: {
    opacity: 0.92,
  },
  dailyQuizOptionKey: {
    color: '#8A9A5B',
    fontSize: 11,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    paddingTop: 1,
  },
  dailyQuizOptionText: {
    flex: 1,
    color: '#E7E1D4',
    fontSize: 14,
    lineHeight: 21,
    fontFamily: 'Inter_400Regular',
  },
  dailyQuizOptionTextCorrect: {
    color: '#dcfce7',
  },
  dailyQuizOptionTextWrong: {
    color: '#fee2e2',
  },
  dailyQuizSavingText: {
    color: '#8A9A5B',
    fontSize: 10,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  dailyQuizExplanationCard: {
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
    backgroundColor: 'rgba(0, 0, 0, 0.22)',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 6,
  },
  dailyQuizExplanationLabel: {
    color: '#8A9A5B',
    fontSize: 10,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  dailyQuizExplanationBody: {
    color: '#DED7C8',
    fontSize: 13,
    lineHeight: 20,
    fontFamily: 'Inter_400Regular',
  },
  dailyQuizStatusCard: {
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
    backgroundColor: 'rgba(15, 15, 15, 0.86)',
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 10,
  },
  dailyQuizStatusTitle: {
    color: '#E5E4E2',
    fontSize: 14,
    lineHeight: 20,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  dailyQuizStatusBody: {
    color: '#c9c6bf',
    fontSize: 13,
    lineHeight: 20,
    fontFamily: 'Inter_400Regular',
  },
  settingsTabRow: {
    flexDirection: 'row',
    gap: 8,
  },
  settingsTabChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.14)',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  settingsTabChipActive: {
    borderColor: '#8A9A5B',
    backgroundColor: 'rgba(138, 154, 91, 0.2)',
  },
  settingsTabChipText: {
    color: '#8e8b84',
    fontSize: 11,
    fontFamily: 'Inter_600SemiBold',
    letterSpacing: 0.35,
    textTransform: 'uppercase',
  },
  settingsTabChipTextActive: {
    color: '#E5E4E2',
  },
  settingsAvatarPickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  settingsAvatarPreviewWrap: {
    width: 64,
    height: 64,
    borderRadius: 999,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(138, 154, 91, 0.2)',
  },
  settingsAvatarPreviewImage: {
    width: '100%',
    height: '100%',
  },
  settingsAvatarPreviewFallback: {
    color: '#E5E4E2',
    fontSize: 20,
    fontFamily: 'Inter_700Bold',
  },
  settingsAvatarActionRow: {
    flex: 1,
    gap: 8,
  },
  settingsGenderRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  settingsGenderChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.14)',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  settingsGenderChipActive: {
    borderColor: '#8A9A5B',
    backgroundColor: 'rgba(138, 154, 91, 0.2)',
  },
  settingsGenderChipText: {
    color: '#8e8b84',
    fontSize: 11,
    fontFamily: 'Inter_500Medium',
  },
  settingsGenderChipTextActive: {
    color: '#E5E4E2',
    fontFamily: 'Inter_600SemiBold',
  },
  settingsPrivacyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  settingsPrivacyRowPressed: {
    opacity: 0.9,
  },
  settingsPrivacyCopy: {
    flex: 1,
    gap: 4,
  },
  settingsPrivacyTitle: {
    color: '#E5E4E2',
    fontSize: 13,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  settingsPrivacyBody: {
    color: '#8e8b84',
    fontSize: 12,
    lineHeight: 18,
    fontFamily: 'Inter_400Regular',
  },
  settingsPrivacyToggle: {
    width: 48,
    height: 30,
    borderRadius: 999,
    paddingHorizontal: 4,
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
  },
  settingsPrivacyToggleActive: {
    backgroundColor: '#8A9A5B',
  },
  settingsPrivacyKnob: {
    width: 22,
    height: 22,
    borderRadius: 999,
    backgroundColor: '#E5E4E2',
  },
  settingsPrivacyKnobActive: {
    backgroundColor: '#121212',
    transform: [{ translateX: 18 }],
  },
  arenaLeaderboardAvatarWrap: {
    width: 30,
    height: 30,
    borderRadius: 999,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    backgroundColor: 'rgba(138, 154, 91, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  arenaLeaderboardAvatarImage: {
    width: '100%',
    height: '100%',
  },
  arenaLeaderboardAvatarFallback: {
    color: '#E5E4E2',
    fontSize: 12,
    fontFamily: 'Inter_700Bold',
  },
  profileBadgeList: {
    marginTop: 8,
    gap: 4,
  },
  profileHeroRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  profileHeroAvatarWrap: {
    width: 72,
    height: 72,
    borderRadius: 999,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.14)',
    backgroundColor: 'rgba(138, 154, 91, 0.2)',
  },
  profileHeroAvatarImage: {
    width: '100%',
    height: '100%',
  },
  profileHeroAvatarFallback: {
    color: '#E5E4E2',
    fontSize: 24,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
  },
  profileHeroContent: {
    flex: 1,
    gap: 2,
  },
  profileSettingsButton: {
    width: 40,
    height: 40,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.14)',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
  },
  profileAboutBox: {
    marginTop: 4,
    padding: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    gap: 8,
  },
  profileIdentityHeroRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  profileIdentityAvatarWrap: {
    width: 68,
    height: 68,
    borderRadius: 999,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    backgroundColor: 'rgba(138, 154, 91, 0.18)',
  },
  profileIdentityAvatarImage: {
    width: '100%',
    height: '100%',
  },
  profileIdentityAvatarFallback: {
    color: '#E5E4E2',
    fontSize: 24,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
  },
  profileIdentityHeroCopy: {
    flex: 1,
    gap: 4,
  },
  profileUnifiedHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  profileUnifiedHeaderCopy: {
    flex: 1,
    gap: 4,
  },
  profileUnifiedSection: {
    gap: 10,
  },
  profileUnifiedDivider: {
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    marginVertical: 2,
  },
  profileUnifiedEmptyText: {
    color: '#8e8b84',
    fontSize: 12,
    lineHeight: 18,
    fontFamily: 'Inter_400Regular',
  },
  profileLinkText: {
    color: '#8A9A5B',
    fontSize: 12,
    fontFamily: 'Inter_600SemiBold',
    textDecorationLine: 'underline',
  },
  profileGenreList: {
    marginTop: 2,
    gap: 8,
  },
  profileGenreRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  profileGenreLabel: {
    color: '#E5E4E2',
    fontSize: 13,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  profileGenreValue: {
    color: '#8e8b84',
    fontSize: 12,
    fontFamily: 'Inter_500Medium',
  },
  discoverRouteSurfaceModal: {
    flex: 1,
    backgroundColor: '#121212',
  },
  discoverRouteSurfaceHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.08)',
    backgroundColor: '#171717',
  },
  discoverRouteSurfaceHeaderCopy: {
    flex: 1,
    gap: 4,
  },
  discoverRouteSurfaceEyebrow: {
    color: '#8e8b84',
    fontSize: 11,
    fontFamily: 'Inter_600SemiBold',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  discoverRouteSurfaceTitle: {
    color: '#E5E4E2',
    fontSize: 18,
    lineHeight: 24,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
  },
  discoverRouteSurfaceActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  discoverRouteSurfaceBody: {
    flex: 1,
    backgroundColor: '#121212',
  },
  discoverRouteSurfaceLoading: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: '#121212',
  },
  discoverRouteSurfaceLoadingText: {
    color: '#c7bcb2',
    fontSize: 13,
    lineHeight: 18,
    fontFamily: 'Inter_500Medium',
  },
  discoverRouteSurfaceErrorCard: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 20,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(164, 94, 74, 0.35)',
    backgroundColor: 'rgba(39, 22, 19, 0.92)',
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 6,
  },
  discoverRouteSurfaceErrorTitle: {
    color: '#fecaca',
    fontSize: 13,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  discoverRouteSurfaceErrorBody: {
    color: '#f1ece1',
    fontSize: 12,
    lineHeight: 18,
    fontFamily: 'Inter_400Regular',
  },
  dawnTextColor: {
    color: '#A45E4A',
  },
  dawnTextMuted: {
    color: '#8B6A5E',
  },
  dawnLinkText: {
    color: '#A45E4A',
  },
});


