import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#121212',
    position: 'relative',
  },
  backdropLayer: {
    ...StyleSheet.absoluteFillObject,
    overflow: 'hidden',
    backgroundColor: '#121212',
  },
  backdropBandTop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 220,
    backgroundColor: 'rgba(138, 154, 91, 0.08)',
  },
  backdropBandBottom: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 220,
    backgroundColor: 'rgba(165, 113, 100, 0.08)',
  },
  backdropRuleVerticalA: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 28,
    width: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
  },
  backdropRuleVerticalB: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    right: 28,
    width: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
  },
  backdropRuleHorizontalA: {
    position: 'absolute',
    top: 132,
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
  },
  backdropRuleHorizontalB: {
    position: 'absolute',
    bottom: 188,
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
  },
  pageMotion: {
    flex: 1,
  },
  container: {
    paddingHorizontal: 18,
    paddingTop: 24,
    paddingBottom: 32,
    gap: 16,
  },
  containerWithTabs: {
    paddingBottom: 126,
  },
  heroCard: {
    position: 'relative',
    backgroundColor: 'rgba(23, 23, 23, 0.85)',
    borderColor: 'rgba(255, 255, 255, 0.1)',
    borderWidth: 1,
    borderRadius: 32,
    paddingHorizontal: 24,
    paddingVertical: 24,
    gap: 8,
    overflow: 'hidden',
    shadowColor: '#121212',
    shadowOpacity: 0.6,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  heroAccent: {
    position: 'absolute',
    top: 12,
    left: 20,
    width: 84,
    height: 5,
    borderRadius: 999,
    backgroundColor: '#8A9A5B',
  },
  heroTicketRow: {
    marginTop: 2,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  heroTicketDotSage: {
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: '#8A9A5B',
  },
  heroTicketDotClay: {
    width: 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: '#A57164',
  },
  heroTicketDash: {
    width: 28,
    height: 2,
    borderRadius: 999,
    backgroundColor: 'rgba(255, 255, 255, 0.24)',
  },
  heroEyebrow: {
    color: '#A57164',
    fontSize: 11,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  title: {
    color: '#E5E4E2',
    fontSize: 29,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
    lineHeight: 34,
  },
  subtitle: {
    color: '#c9c6bf',
    fontSize: 14,
    fontFamily: 'Inter_500Medium',
    lineHeight: 20,
    marginBottom: 8,
  },
  heroMetaRow: {
    marginTop: 0,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  surfaceIntroCard: {
    backgroundColor: 'rgba(23, 23, 23, 0.85)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 10,
  },
  surfaceIntroAccent: {
    width: 34,
    height: 4,
    borderRadius: 999,
  },
  surfaceIntroAccentSage: {
    backgroundColor: '#8A9A5B',
  },
  surfaceIntroAccentClay: {
    backgroundColor: '#A57164',
  },
  surfaceIntroTitle: {
    color: '#E5E4E2',
    fontSize: 15,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
  },
  surfaceIntroBody: {
    color: '#c9c6bf',
    fontSize: 12,
    fontFamily: 'Inter_400Regular',
    lineHeight: 18,
  },
  surfaceIntroMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  surfaceIntroBadge: {
    backgroundColor: 'rgba(138, 154, 91, 0.18)',
    borderColor: '#8A9A5B',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    color: '#E5E4E2',
    fontSize: 11,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  surfaceIntroBadgeMuted: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderColor: 'rgba(255, 255, 255, 0.24)',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    color: '#E5E4E2',
    fontSize: 11,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  navScene: {
    backgroundColor: '#121212',
  },
  navTabBar: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 16,
    backgroundColor: 'rgba(18, 18, 18, 0.92)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderRadius: 32,
    height: 74,
    paddingBottom: 10,
    paddingTop: 8,
    shadowColor: '#121212',
    shadowOpacity: 0.5,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  navTabLabel: {
    fontSize: 11,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
    letterSpacing: 0.45,
    textTransform: 'uppercase',
  },
  navTabItem: {
    paddingTop: 4,
  },
  navTabBadge: {
    backgroundColor: '#A57164',
    color: '#E5E4E2',
    borderColor: '#171717',
    borderWidth: 1,
    fontSize: 10,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '700',
    minWidth: 18,
    height: 18,
    paddingHorizontal: 4,
    lineHeight: 13,
    borderRadius: 999,
    top: 2,
  },
  bottomTabBar: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 10,
    backgroundColor: 'rgba(23, 23, 23, 0.95)',
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderWidth: 1,
    borderRadius: 16,
    padding: 8,
  },
  bottomTabRow: {
    flexDirection: 'row',
    gap: 8,
  },
  statusRail: {
    marginTop: 6,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  opsSummaryRow: {
    marginTop: 2,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  opsSummaryCard: {
    minWidth: 98,
    flexGrow: 1,
    backgroundColor: 'rgba(31, 31, 31, 0.7)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 4,
  },
  opsSummaryKey: {
    color: '#8e8b84',
    fontSize: 10,
    fontFamily: 'Inter_500Medium',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  opsSummaryValue: {
    color: '#E5E4E2',
    fontSize: 13,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
  },
  statusPill: {
    minWidth: 96,
    flexGrow: 1,
    backgroundColor: 'rgba(31, 31, 31, 0.7)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 4,
  },
  statusPillKey: {
    color: '#8e8b84',
    fontSize: 10,
    fontFamily: 'Inter_500Medium',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  statusPillValue: {
    color: '#E5E4E2',
    fontSize: 12,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  statusPillValueSage: {
    color: '#8A9A5B',
  },
  statusPillValueClay: {
    color: '#A57164',
  },
  heroBadge: {
    backgroundColor: 'rgba(138, 154, 91, 0.18)',
    borderColor: '#8A9A5B',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    color: '#E5E4E2',
    fontSize: 11,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  heroBadgeMuted: {
    backgroundColor: 'rgba(165, 113, 100, 0.18)',
    borderColor: '#A57164',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    color: '#E5E4E2',
    fontSize: 11,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  heroBadgeNeutral: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderColor: 'rgba(255, 255, 255, 0.26)',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    color: '#E5E4E2',
    fontSize: 11,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  screenCard: {
    backgroundColor: 'rgba(23, 23, 23, 0.85)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderRadius: 24,
    padding: 20,
    gap: 14,
    shadowColor: '#121212',
    shadowOpacity: 0.4,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 6,
  },
  screenCardAccent: {
    width: 48,
    height: 4,
    borderRadius: 999,
    marginBottom: 2,
  },
  screenCardAccentSage: {
    backgroundColor: '#8A9A5B',
  },
  screenCardAccentClay: {
    backgroundColor: '#A57164',
  },
  screenTitle: {
    color: '#E5E4E2',
    fontSize: 19,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
  },
  screenBody: {
    color: '#c9c6bf',
    fontSize: 14,
    fontFamily: 'Inter_400Regular',
    lineHeight: 21,
  },
  screenMeta: {
    color: '#8e8b84',
    fontSize: 12,
    fontFamily: 'Inter_400Regular',
  },
  movieList: {
    marginTop: 8,
    gap: 8,
  },
  movieRow: {
    padding: 12,
    backgroundColor: 'rgba(31, 31, 31, 0.7)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  movieTitle: {
    color: '#E5E4E2',
    fontSize: 14,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  movieMeta: {
    marginTop: 4,
    color: '#8e8b84',
    fontSize: 12,
    fontFamily: 'Inter_400Regular',
  },
  inboxList: {
    marginTop: 6,
  },
  inboxItemSeparator: {
    height: 8,
  },
  inboxRow: {
    backgroundColor: 'rgba(31, 31, 31, 0.7)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 6,
  },
  inboxTitle: {
    color: '#E5E4E2',
    fontSize: 12,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '700',
  },
  inboxTitleState: {
    color: '#8e8b84',
    fontSize: 11,
    fontFamily: 'Inter_500Medium',
    fontWeight: '600',
  },
  inboxMeta: {
    color: '#8e8b84',
    fontSize: 11,
    fontFamily: 'Inter_400Regular',
  },
  inboxBody: {
    color: '#E5E4E2',
    fontSize: 12,
    fontFamily: 'Inter_400Regular',
  },
  inboxHighlight: {
    backgroundColor: 'rgba(138, 154, 91, 0.24)',
    color: '#E5E4E2',
    borderRadius: 4,
    overflow: 'hidden',
  },
  inboxOpenButton: {
    marginTop: 4,
    alignSelf: 'flex-start',
    backgroundColor: '#8A9A5B',
    borderRadius: 12,
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 10,
    justifyContent: 'center',
  },
  inboxActionRow: {
    marginTop: 4,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  inboxCopyButton: {
    marginTop: 4,
    alignSelf: 'flex-start',
    backgroundColor: '#A57164',
    borderRadius: 12,
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 10,
    justifyContent: 'center',
  },
  inboxBulkOpenButton: {
    marginTop: 4,
    alignSelf: 'flex-start',
    backgroundColor: '#8A9A5B',
    borderRadius: 12,
    minHeight: 44,
    paddingHorizontal: 14,
    paddingVertical: 10,
    justifyContent: 'center',
  },
  inboxBulkRemoveButton: {
    marginTop: 4,
    alignSelf: 'flex-start',
    backgroundColor: '#7f1d1d',
    borderRadius: 12,
    minHeight: 44,
    paddingHorizontal: 14,
    paddingVertical: 10,
    justifyContent: 'center',
  },
  inboxFilterRow: {
    marginTop: 6,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  inboxSearchInput: {
    marginTop: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderRadius: 12,
    color: '#E5E4E2',
    fontSize: 13,
    fontFamily: 'Inter_400Regular',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  inboxSortRow: {
    marginTop: 6,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  inboxPaginationRow: {
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  inboxPageButton: {
    backgroundColor: '#8A9A5B',
    borderRadius: 8,
    minHeight: 44,
    paddingHorizontal: 10,
    paddingVertical: 6,
    justifyContent: 'center',
  },
  inboxPaginationText: {
    color: '#E5E4E2',
    fontSize: 12,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  ritualInput: {
    minHeight: 100,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderRadius: 14,
    color: '#E5E4E2',
    fontSize: 14,
    fontFamily: 'Inter_400Regular',
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  ritualMetaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  ritualStateOk: {
    color: '#8A9A5B',
  },
  ritualStateWarn: {
    color: '#A57164',
  },
  ritualStateError: {
    color: '#fca5a5',
  },
  ritualActionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  profileGrid: {
    marginTop: 6,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  profileMetricCard: {
    minWidth: 90,
    flexGrow: 1,
    backgroundColor: 'rgba(31, 31, 31, 0.7)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 4,
  },
  profileMetricValue: {
    color: '#E5E4E2',
    fontSize: 16,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
  },
  profileMetricLabel: {
    color: '#8e8b84',
    fontSize: 11,
    fontFamily: 'Inter_500Medium',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  badgeRow: {
    marginTop: 4,
    gap: 2,
  },
  warningBox: {
    marginTop: 6,
    padding: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#A57164',
    backgroundColor: 'rgba(165, 113, 100, 0.14)',
  },
  warningText: {
    color: '#A57164',
    fontSize: 12,
    fontFamily: 'Inter_500Medium',
  },
  exploreRouteList: {
    marginTop: 6,
    gap: 10,
  },
  exploreRouteRow: {
    backgroundColor: 'rgba(31, 31, 31, 0.7)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderRadius: 16,
    padding: 14,
    gap: 12,
  },
  exploreRouteContent: {
    gap: 4,
  },
  exploreRouteTitle: {
    color: '#E5E4E2',
    fontSize: 13,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  exploreRouteBody: {
    color: '#8e8b84',
    fontSize: 12,
    fontFamily: 'Inter_400Regular',
    lineHeight: 18,
  },
  exploreRouteAction: {
    alignSelf: 'flex-start',
  },
  arenaMetricGrid: {
    marginTop: 6,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  arenaMetricCard: {
    minWidth: 92,
    flexGrow: 1,
    backgroundColor: 'rgba(31, 31, 31, 0.7)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 4,
  },
  arenaMetricValue: {
    color: '#E5E4E2',
    fontSize: 15,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
  },
  arenaMetricLabel: {
    color: '#8e8b84',
    fontSize: 10,
    fontFamily: 'Inter_500Medium',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  arenaLeaderboardList: {
    marginTop: 4,
    gap: 8,
  },
  arenaLeaderboardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: 'rgba(31, 31, 31, 0.7)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  arenaLeaderboardRankWrap: {
    width: 24,
    height: 24,
    borderRadius: 999,
    backgroundColor: 'rgba(138, 154, 91, 0.18)',
    borderColor: '#8A9A5B',
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  arenaLeaderboardRank: {
    color: '#E5E4E2',
    fontSize: 11,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
  },
  arenaLeaderboardContent: {
    flex: 1,
    gap: 2,
  },
  arenaLeaderboardName: {
    color: '#E5E4E2',
    fontSize: 12,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  arenaLeaderboardMeta: {
    color: '#8e8b84',
    fontSize: 11,
    fontFamily: 'Inter_400Regular',
  },
  arenaLeaderboardAction: {
    minWidth: 74,
  },
  publicProfileInput: {
    marginTop: 2,
    backgroundColor: '#141414',
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderWidth: 1,
    borderRadius: 10,
    color: '#E5E4E2',
    fontSize: 12,
    fontFamily: 'Inter_400Regular',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  rulesList: {
    marginTop: 4,
    gap: 8,
  },
  rulesRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  rulesDot: {
    marginTop: 7,
    width: 5,
    height: 5,
    borderRadius: 999,
    backgroundColor: '#8A9A5B',
  },
  rulesText: {
    flex: 1,
    color: '#c9c6bf',
    fontSize: 12,
    lineHeight: 18,
    fontFamily: 'Inter_400Regular',
  },
  actionsRow: {
    flexDirection: 'row',
    gap: 10,
    backgroundColor: '#1f1f1f',
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderWidth: 1,
    borderRadius: 14,
    padding: 10,
  },
  actionsHint: {
    marginTop: -6,
    paddingHorizontal: 4,
    color: '#8e8b84',
    fontSize: 11,
    fontFamily: 'Inter_500Medium',
  },
  singleActionRow: {
    backgroundColor: '#1f1f1f',
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderWidth: 1,
    borderRadius: 14,
    padding: 10,
  },
  sectionHeaderRow: {
    marginTop: 4,
    marginBottom: 0,
    paddingHorizontal: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  sectionAnchor: {
    marginTop: 2,
  },
  quickNavRow: {
    marginTop: 2,
    flexDirection: 'row',
    gap: 8,
    backgroundColor: '#171717',
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderWidth: 1,
    borderRadius: 12,
    padding: 8,
  },
  quickNavHint: {
    marginTop: -4,
    paddingHorizontal: 4,
    color: '#8e8b84',
    fontSize: 11,
    fontFamily: 'Inter_500Medium',
  },
  backToTopWrap: {
    position: 'absolute',
    right: 14,
    bottom: 22,
    width: 110,
    gap: 8,
  },
  backToTopMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#171717',
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  backToTopMetaKey: {
    color: '#8e8b84',
    fontSize: 10,
    fontFamily: 'Inter_500Medium',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  backToTopMetaValue: {
    color: '#E5E4E2',
    fontSize: 10,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  backToTopQuickRow: {
    flexDirection: 'row',
    gap: 8,
  },
  sectionHeader: {
    color: '#E5E4E2',
    fontSize: 11,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
    letterSpacing: 0.9,
    textTransform: 'uppercase',
  },
  sectionHeaderMeta: {
    color: '#8e8b84',
    fontSize: 11,
    fontFamily: 'Inter_500Medium',
  },
  subSectionLabel: {
    marginTop: 2,
    color: '#8e8b84',
    fontSize: 10,
    fontFamily: 'Inter_600SemiBold',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  retryButton: {
    marginTop: 8,
    alignSelf: 'flex-start',
    backgroundColor: '#8A9A5B',
    borderRadius: 999,
    minHeight: 48,
    paddingHorizontal: 20,
    paddingVertical: 12,
    justifyContent: 'center',
    shadowColor: '#8A9A5B',
    shadowOpacity: 0.15,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  retryText: {
    color: '#E5E4E2',
    fontSize: 12,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  authForm: {
    marginTop: 8,
    gap: 8,
  },
  authSignedInBox: {
    marginTop: 8,
    gap: 8,
  },
  input: {
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderRadius: 14,
    color: '#E5E4E2',
    fontSize: 14,
    fontFamily: 'Inter_400Regular',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  claimButton: {
    marginTop: 6,
    alignSelf: 'flex-start',
    backgroundColor: '#8A9A5B',
    borderRadius: 999,
    minHeight: 48,
    paddingHorizontal: 24,
    paddingVertical: 12,
    justifyContent: 'center',
    shadowColor: '#8A9A5B',
    shadowOpacity: 0.2,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
  },
  claimButtonDisabled: {
    opacity: 0.7,
  },
  claimButtonText: {
    color: '#E5E4E2',
    fontSize: 12,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  signOutButton: {
    alignSelf: 'flex-start',
    backgroundColor: '#7f1d1d',
    borderRadius: 999,
    minHeight: 48,
    paddingHorizontal: 20,
    paddingVertical: 12,
    justifyContent: 'center',
  },
  claimSuccess: {
    marginTop: 6,
    padding: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#8A9A5B',
    backgroundColor: 'rgba(138, 154, 91, 0.14)',
    gap: 2,
  },
  claimSuccessText: {
    color: '#d9e2bf',
    fontSize: 12,
    fontFamily: 'Inter_500Medium',
    fontWeight: '600',
  },
  claimError: {
    marginTop: 6,
    padding: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#7f1d1d',
    backgroundColor: 'rgba(127, 29, 29, 0.24)',
    gap: 2,
  },
  claimErrorText: {
    color: '#fecaca',
    fontSize: 12,
    fontFamily: 'Inter_500Medium',
    fontWeight: '600',
  },
  card: {
    backgroundColor: 'rgba(31, 31, 31, 0.7)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
    gap: 12,
  },
  cardTitle: {
    color: '#E5E4E2',
    fontSize: 14,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  code: {
    color: '#c9c6bf',
    fontFamily: 'monospace',
    fontSize: 12,
    lineHeight: 18,
  },
  /* Theme Mode Classes (Dawn support & Glassmorphic Toggle) */
  safeAreaDawn: {
    backgroundColor: '#1E1E1E',
  },
  backdropLayerDawn: {
    backgroundColor: '#FAF9F6',
  },
  navSceneDawn: {
    backgroundColor: '#FAF9F6',
  },
  navTabBarDawn: {
    backgroundColor: 'rgba(250, 249, 246, 0.95)',
    borderColor: 'rgba(0, 0, 0, 0.08)',
  },
  themeModeSegmentContainer: {
    marginTop: 8,
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderRadius: 12,
    padding: 6,
    gap: 6,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
  },
  themeModeSegmentOption: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    backgroundColor: 'transparent',
  },
  themeModeSegmentActiveMidnight: {
    backgroundColor: 'rgba(31, 31, 31, 0.9)',
    shadowColor: '#000000',
    shadowOpacity: 0.3,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
    borderColor: '#8A9A5B',
    borderWidth: 1,
  },
  themeModeSegmentActiveDawn: {
    backgroundColor: 'rgba(165, 113, 100, 0.9)', // Clay accent for Dawn
    shadowColor: '#A57164',
    shadowOpacity: 0.4,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
    borderColor: 'rgba(255, 255, 255, 0.4)',
    borderWidth: 1,
  },
  themeModeSegmentText: {
    color: '#8e8b84',
    fontSize: 13,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
  },
  themeModeSegmentTextActiveMidnight: {
    color: '#E5E4E2',
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
  },
  themeModeSegmentTextActiveDawn: {
    color: '#FFFFFF',
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
  },

  /* Comment Feed Classes */
  commentFeedFilterRow: {
    marginTop: 10,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  commentFeedSortRow: {
    marginTop: 6,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  commentFeedSearchInput: {
    marginTop: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderRadius: 14,
    color: '#E5E4E2',
    fontSize: 14,
    fontFamily: 'Inter_400Regular',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  commentFeedList: {
    marginTop: 12,
    gap: 12,
  },
  commentFeedRow: {
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.06)',
    backgroundColor: 'rgba(31, 31, 31, 0.5)',
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 8,
  },
  commentFeedRowHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  commentFeedMovieTitle: {
    flex: 1,
    color: '#E5E4E2',
    fontSize: 13,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  commentFeedMineBadge: {
    color: '#E5E4E2',
    fontSize: 9,
    fontFamily: 'Inter_700Bold',
    fontWeight: '700',
    letterSpacing: 0.5,
    backgroundColor: 'rgba(138, 154, 91, 0.24)',
    borderColor: '#8A9A5B',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 7,
    paddingVertical: 2,
    overflow: 'hidden',
    textTransform: 'uppercase',
  },
  commentFeedMeta: {
    color: '#8e8b84',
    fontSize: 11,
    fontFamily: 'Inter_500Medium',
  },
  commentFeedBody: {
    color: '#E5E4E2',
    fontSize: 13,
    fontFamily: 'Inter_400Regular',
    lineHeight: 20,
    marginTop: 2,
    marginBottom: 2,
  },
  commentFeedActionRow: {
    marginTop: 4,
    alignItems: 'flex-start',
  },

  /* Profile Mark Classes */
  markPillRow: {
    marginTop: 8,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  markCategoryList: {
    gap: 12,
  },
  markCategoryBlock: {
    gap: 8,
  },
  markCategoryTitle: {
    color: '#8e8b84',
    fontSize: 11,
    fontFamily: 'Inter_600SemiBold',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  markPill: {
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    backgroundColor: 'rgba(45, 45, 45, 0.6)',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  markPillText: {
    color: '#E5E4E2',
    fontSize: 12,
    fontFamily: 'Inter_500Medium',
  },
  markPillFeatured: {
    borderWidth: 1,
    borderColor: '#D4AF37', // Gold Premium Outline
    backgroundColor: 'rgba(212, 175, 55, 0.15)', // Light Gold fill
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 8,
    shadowColor: '#D4AF37',
    shadowOpacity: 0.4,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },
  markPillFeaturedText: {
    color: '#fef08a', // vibrant gold text
    fontSize: 13,
    fontFamily: 'Inter_600SemiBold',
    fontWeight: '600',
    textShadowColor: 'rgba(212, 175, 55, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
});


